### ISSUE TITLE
[Test] Test error 

### ISSUE THREAD

**Issue by lshoo** [LeonHartley/Coerce-rs#13]
I got errors when I run cargo test:
```
running 3 tests
test test_redis_journal_actor_integration ... ok
test test_redis_journal_read_write_snapshot ... FAILED
test test_redis_journal_read_write_messages ... FAILED
```
or cargo nextest run --workspace:
```
        PASS [   0.027s] coerce::test_remote_sharding test_shard_coordinator_shard_allocation
        PASS [   0.035s] coerce::test_remote_actor_creation test_remote_actor_deploy_remotely
        PASS [   0.056s] coerce::test_actor_supervision test_actor_child_spawn_and_stop
        PASS [   0.530s] coerce::test_remote_sharding_rebalancing test_shard_rebalancing_upon_node_termination
        PASS [   2.011s] coerce::test_remote_system_health test_heartbeat_actor_monitoring
------------
     Summary [   2.035s] 38/47 tests run: 31 passed, 7 failed, 0 skipped
        FAIL [   0.016s] coerce::test_remote_actor_err test_remote_actor_err
        FAIL [   0.019s] coerce::test_remote_actor_locate test_remote_actor_locate_remotely
        FAIL [   0.018s] coerce::test_remote_api test_remote_api_routes
        FAIL [   0.027s] coerce::test_remote_cluster_formation test_remote_cluster_workers
        FAIL [   0.025s] coerce::test_remote_cluster_heartbeat test_remote_cluster_heartbeat
        FAIL [   0.019s] coerce::test_remote_pubsub test_pubsub_distributed
        FAIL [   0.014s] coerce::test_remote_sharding test_shard_host_actor_request
```
How to fix or config for these errors? 
I clone the main branch, the os is wsl2 + ubuntu 22.04, rust version is 1.68.2.

Thanks

**Comment by lshoo** [comment]
I want to run the cluster example, but I got errors when i `cargo run -p coerce-cluster-example`:
```
error[E0432]: unresolved import `crate::remote::net::security::jwt`
  --> coerce/src/remote/system/builder.rs:27:35
   |
27 | use crate::remote::net::security::jwt::Jwt;
   |                                   ^^^ could not find `jwt` in `security`

error[E0432]: unresolved import `crate::remote::net::security::jwt`
 --> coerce/src/remote/net/security/auth/mod.rs:1:35
  |
1 | use crate::remote::net::security::jwt::Jwt;
  |                                   ^^^ could not find `jwt` in `security`
```

**Comment by lshoo** [comment]
When I remove coerce-rs features `full` or `remote` of dependencies from `Cargo.toml` like this：
```
coerce = { version = "0", features = [] }
```
It works，but how to enable `remote` feature?

**Comment by LeonHartley** [comment]
Hi @lshoo!

I've updated the main readme with some documentation about the issue you're seeing with errors related to `value::Valuable`.

https://github.com/LeonHartley/Coerce-rs#using-coerce-in-your-own-project

The errors related to utoipa look to have been caused by their recent updates, I've updated the crate versions which has resolved the issue. I'll be pushing a crate update (0.8.6) momentarily. 

Thanks for trying Coerce out!

Leon

**Comment by lshoo** [comment]
@LeonHartley 
Thanks for your answer!

I'm an Akka user before，e.g. Akka-Cluster, Akka-persistence, I like these features.
I want to use Coerce these features too.

But i don't find cluster docs now.

lshoo

**Comment by LeonHartley** [comment]
Hey @lshoo,

Thank you!

I'm sorry but the docs around remote and clustering is still somewhat lacking. I'm hoping to spend some more time on documentation very soon.

Check out the [sharded chat example](https://github.com/LeonHartley/Coerce-rs/tree/master/examples/coerce-sharded-chat-example), which utilizes most of the features offered by Coerce, including persistence and clustering.
Also please check out the remote section on [docs.rs/coerce](https://docs.rs/coerce/0.8.7/coerce/, while it still needs a *lot* of work, there are some important points mentioned.

Leon

**Comment by lshoo** [comment]
Hi @LeonHartley 
Thanks！

I can run coerce-cluster-example after updated 0.8.7 in Coerce source code。
but In my project，When I run `cargo check` , I also got some errors like `valuable::Value<'_>: tracing::Value`  after updatet 0.8.7 and add：
```
coerce = { version = "0.8", features = ["full"]}

[build]
rustflags = ["--cfg", "tracing_unstable"]
```

the code repo: [coerce-actor](https://github.com/lshoo/coerce-actor)

Do I miss something?
---
by lshoo

**Comment by LeonHartley** [comment]
Hey @lshoo,

The `[build]` section needs to go in `.cargo/config.toml` .

Cheers,
Leon

**Comment by lshoo** [comment]
Thanks! @LeonHartley 

It works

Cheers,
lshoo
