### ISSUE TITLE
Actor stops receiving messages after a panic

### ISSUE THREAD

**Issue by milosimr** [LeonHartley/Coerce-rs#33]
If a panic occurs in an actor message handler, that actor stops receiving the message, and is only returning this error:

`failed to send message, ref is no longer valid`

Are there any extra steps needed to make sure the supervisor is running and can restart the actor in these cases?

Thanks

**Comment by LeonHartley** [comment]
Hi @milosimr - actor watching, and with that - manual actor supervision is not possible up-to Coerce 8.10, however in the next release (8.11), this functionality will be there.

The code is currently in the master branch, but I have not released 8.11 yet: 
https://github.com/LeonHartley/Coerce-rs/blob/master/coerce/tests/test_actor_watching.rs

I will try and get 8.11 released ASAP so you can give this feature a try!

Cheers,
Leon

**Comment by milosimr** [comment]
Thanks @LeonHartley, I'll try using master branch for my app until 8.11 is released. Is there any documentation on setting up actor supervision, or is that test enough?

**Comment by milosimr** [comment]
Thanks for all the great work.
