### ISSUE TITLE
Great library

### ISSUE THREAD

**Issue by Swoorup** [LeonHartley/Coerce-rs#6]
Just wanted to say thanks for the great library. It is neatly designed, I tested around 2 other libraries (Zester, puppet), in which this one had the right balance. 

* It had a nice api to use via rust trait handlers as opposed to writing event loop.
* Sufficiently feature complete. 
* The Actor trait has lifestyle methods I could use to hook in custom stuffs.

Few comments: 
* At a glance the naming is bit confusing as to what the project is about. 
* Any plans to support async trait as in https://blog.rust-lang.org/inside-rust/2022/11/17/async-fn-in-trait-nightly.html ?

**Comment by LeonHartley** [comment]
Hi @Swoorup!

Thanks for your kind words, I'm glad you like it. Once `async fn in trait` is generally available in stable Rust, I plan on dropping the async-trait dependency altogether. 

The name was something we planned on using for a something related to push notifications in a very very old project and I just stuck with it. I'm thinking of changing the name of this library prior to 1.0 release, with something a little more fitting - I definitely understand the confusion and the negative connotations the word coerce has. 

Thanks again,
Leon
